"""
This type stub file was generated by pyright.
"""

import abc
import numpy as np

IMAGEIO_SUPPORT = ...
class BaseVisualizer(abc.ABC):
    """
    Pinocchio visualizers are employed to easily display a model at a given
    configuration.
    BaseVisualizer is not meant to be directly employed, but only to provide a uniform
    interface and a few common methods.
    New visualizers should extend this class and override its methods as neeeded.
    """
    _video_writer = ...
    _video_writer = ...
    def __init__(self, model=..., collision_model=..., visual_model=..., copy_models=..., data=..., collision_data=..., visual_data=...) -> None:
        """
        Construct a display from the given model, collision model, and visual model.
        If copy_models is True, the models are copied. Otherwise, they are simply kept
        as a reference.
        """
        ...
    
    def rebuildData(self): # -> None:
        """Re-build the data objects. Needed if the models were modified.
        Warning: this will delete any information stored in all data objects."""
        ...
    
    def getViewerNodeName(self, geometry_object, geometry_type): # -> None:
        """Return the name of the geometry object inside the viewer."""
        ...
    
    def initViewer(self, *args, **kwargs): # -> None:
        """Init the viewer by loading the gui and creating a window."""
        ...
    
    def loadViewerModel(self, *args, **kwargs): # -> None:
        """Create the scene displaying the robot meshes in the viewer"""
        ...
    
    def reload(self, new_geometry_object, geometry_type=...): # -> None:
        """Reload a geometry_object given by its type"""
        ...
    
    def clean(self): # -> None:
        """Delete all the objects from the whole scene"""
        ...
    
    @abc.abstractmethod
    def display(self, q=...): # -> None:
        """
        Display the robot at configuration q or refresh the rendering
        from the current placements contained in data by placing all the bodies in the
        viewer.
        """
        ...
    
    @abc.abstractmethod
    def displayCollisions(self, visibility): # -> None:
        """Set whether to display collision objects or not."""
        ...
    
    @abc.abstractmethod
    def displayVisuals(self, visibility): # -> None:
        """Set whether to display visual objects or not."""
        ...
    
    @abc.abstractmethod
    def setBackgroundColor(self): # -> None:
        """Set the visualizer background color."""
        ...
    
    @abc.abstractmethod
    def setCameraTarget(self, target): # -> None:
        """Set the camera target."""
        ...
    
    @abc.abstractmethod
    def setCameraPosition(self, position: np.ndarray): # -> None:
        """Set the camera's 3D position."""
        ...
    
    @abc.abstractmethod
    def setCameraZoom(self, zoom: float): # -> None:
        """Set camera zoom value."""
        ...
    
    @abc.abstractmethod
    def setCameraPose(self, pose: np.ndarray = ...): # -> None:
        """Set camera 6D pose using a 4x4 matrix."""
        ...
    
    @abc.abstractmethod
    def captureImage(self, w=..., h=...): # -> None:
        """Captures an image from the viewer and returns an RGB array."""
        ...
    
    @abc.abstractmethod
    def disableCameraControl(self): # -> None:
        """Disable camera manual control"""
        ...
    
    @abc.abstractmethod
    def enableCameraControl(self): # -> None:
        """Enable camera manual control"""
        ...
    
    @abc.abstractmethod
    def drawFrameVelocities(self, *args, **kwargs): # -> None:
        """Draw current frame velocities."""
        ...
    
    def sleep(self, dt): # -> None:
        ...
    
    def has_video_writer(self): # -> bool:
        ...
    
    def play(self, q_trajectory, dt=..., callback=..., capture=..., **kwargs): # -> list[Any] | None:
        """
        Play a trajectory with given time step. Optionally capture RGB images and
        returns them.
        """
        ...
    
    def create_video_ctx(self, filename=..., fps=..., directory=..., **kwargs): # -> nullcontext[None] | VideoContext:
        """
        Create a video recording context, generating the output filename if necessary.

        Code inspired from https://github.com/petrikvladimir/RoboMeshCat.
        """
        ...
    


class VideoContext:
    def __init__(self, viz, fps, filename, **kwargs) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


__all__ = ["BaseVisualizer"]
