"""
This type stub file was generated by pyright.
"""

import numpy as np
from . import BaseVisualizer

WITH_HPP_FCL_BINDINGS = ...
class GepettoVisualizer(BaseVisualizer):
    """A Pinocchio display using Gepetto Viewer"""
    def getViewerNodeName(self, geometry_object, geometry_type): # -> None:
        """Return the name of the geometry object inside the viewer"""
        ...
    
    def initViewer(self, viewer=..., windowName=..., sceneName=..., loadModel=...): # -> None:
        """Init GepettoViewer by loading the gui and creating a window."""
        ...
    
    def loadPrimitive(self, meshName, geometry_object): # -> bool | None:
        ...
    
    def loadViewerGeometryObject(self, geometry_object, geometry_type): # -> None:
        """Load a single geometry object"""
        ...
    
    def loadViewerModel(self, rootNodeName=...): # -> None:
        """Create the scene displaying the robot meshes in gepetto-viewer"""
        ...
    
    def display(self, q=...): # -> None:
        """
        Display the robot at configuration q in the viewer by placing all the bodies.
        """
        ...
    
    def displayCollisions(self, visibility): # -> None:
        """Set whether to display collision objects or not"""
        ...
    
    def displayVisuals(self, visibility): # -> None:
        """Set whether to display visual objects or not"""
        ...
    
    def setBackgroundColor(self):
        ...
    
    def setCameraTarget(self, target):
        ...
    
    def setCameraPosition(self, position: np.ndarray):
        ...
    
    def setCameraZoom(self, zoom: float):
        ...
    
    def setCameraPose(self, pose: np.ndarray):
        ...
    
    def captureImage(self, w=..., h=...):
        ...
    
    def disableCameraControl(self):
        ...
    
    def enableCameraControl(self):
        ...
    
    def drawFrameVelocities(self, *args, **kwargs):
        ...
    


__all__ = ["GepettoVisualizer"]
