"""
This type stub file was generated by pyright.
"""

import numpy as np
import meshcat.geometry as mg
import hppfcl
from typing import Any, ClassVar
from .. import pinocchio_pywrap_default as pin
from . import BaseVisualizer

MsgType = ...
WITH_HPP_FCL_BINDINGS = ...
DEFAULT_COLOR_PROFILES = ...
COLOR_PRESETS = ...
FRAME_AXIS_POSITIONS = np.array([[0, 0, 0], [1, 0, 0], [0, 0, 0], [0, 1, 0], [0, 0, 0], [0, 0, 1]]).astype(np.float32).T
FRAME_AXIS_COLORS = np.array([[1, 0, 0], [1, 0.6, 0], [0, 1, 0], [0.6, 1, 0], [0, 0, 1], [0, 0.6, 1]]).astype(np.float32).T
def getColor(color): # -> ndarray[Any, Any]:
    ...

def hasMeshFileInfo(geometry_object): # -> bool:
    """Check whether the geometry object contains a Mesh supported by MeshCat"""
    ...

def applyScalingOnHomegeneousTransform(homogeneous_transform: np.ndarray, scale: np.ndarray) -> np.ndarray:
    ...

if import_meshcat_succeed:
    class Cone(mg.Geometry):
        """A cone of the given height and radius. By Three.js convention, the axis
        of rotational symmetry is aligned with the y-axis.
        """
        def __init__(self, height: float, radius: float, radialSegments: float = ..., openEnded: bool = ...) -> None:
            ...
        
        def lower(self, object_data: Any) -> MsgType:
            ...
        
    
    
    class DaeMeshGeometry(mg.ReferenceSceneElement):
        def __init__(self, dae_path: str, cache: set[str] | None = ...) -> None:
            """Load Collada files with texture images.
            Inspired from
            https://gist.github.com/danzimmerman/a392f8eadcf1166eb5bd80e3922dbdc5
            """
            ...
        
        def lower(self) -> dict[str, Any]:
            """Pack data into a dictionary of the format that must be passed to
            `Visualizer.window.send`.
            """
            ...
        
        def set_scale(self, scale) -> None:
            ...
        
    
    
    class Plane(mg.Geometry):
        """A plane of the given width and height."""
        def __init__(self, width: float, height: float, widthSegments: float = ..., heightSegments: float = ...) -> None:
            ...
        
        def lower(self, object_data: Any) -> MsgType:
            ...
        
    
    
if (WITH_HPP_FCL_BINDINGS and tuple(map(int, hppfcl.__version__.split("."))) >= (3, 0, 0) and hppfcl.WITH_OCTOMAP):
    def loadOctree(octree: hppfcl.OcTree): # -> None:
        ...
    
else:
    def loadOctree(octree):
        ...
    
if WITH_HPP_FCL_BINDINGS:
    def loadMesh(mesh):
        ...
    
else:
    def loadMesh(mesh):
        ...
    
def loadPrimitive(geometry_object): # -> RotatedCylinder | None:
    ...

def createCapsule(length, radius, radial_resolution=..., cap_resolution=...):
    ...

class MeshcatVisualizer(BaseVisualizer):
    """A Pinocchio display using Meshcat"""
    FORCE_SCALE = ...
    FRAME_VEL_COLOR = ...
    CAMERA_PRESETS: ClassVar = ...
    def __init__(self, model=..., collision_model=..., visual_model=..., copy_models=..., data=..., collision_data=..., visual_data=...) -> None:
        ...
    
    def getViewerNodeName(self, geometry_object, geometry_type): # -> None:
        """Return the name of the geometry object inside the viewer."""
        ...
    
    def initViewer(self, viewer=..., open=..., loadModel=..., zmq_url=...): # -> None:
        """Start a new MeshCat server and client.
        Note: the server can also be started separately using the "meshcat-server"
        command in a terminal:
        this enables the server to remain active after the current script ends.
        """
        ...
    
    def reset(self): # -> None:
        ...
    
    def setBackgroundColor(self, preset_name: str = ..., col_top=..., col_bot=...): # -> None:
        """Set the background."""
        ...
    
    def setCameraTarget(self, target: np.ndarray): # -> None:
        ...
    
    def setCameraPosition(self, position: np.ndarray): # -> None:
        ...
    
    def setCameraPreset(self, preset_key: str): # -> None:
        """Set the camera angle and position using a given preset."""
        ...
    
    def setCameraZoom(self, zoom: float): # -> None:
        ...
    
    def setCameraPose(self, pose): # -> None:
        ...
    
    def disableCameraControl(self): # -> None:
        ...
    
    def enableCameraControl(self): # -> None:
        ...
    
    def loadPrimitive(self, geometry_object: pin.GeometryObject): # -> RotatedCylinder | TranslatedPlane | TransformedPlane | None:
        ...
    
    def loadMeshFromFile(self, geometry_object): # -> DaeMeshGeometry | None:
        ...
    
    def loadViewerGeometryObject(self, geometry_object, geometry_type, color=...):
        """Load a single geometry object"""
        ...
    
    def loadViewerModel(self, rootNodeName=..., color=..., collision_color=..., visual_color=...): # -> None:
        """Load the robot in a MeshCat viewer.
        Parameters:
            rootNodeName: name to give to the robot in the viewer
            color: deprecated and optional, color to give to both the collision
                and visual models of the robot. This setting overwrites any color
                specified in the robot description. Format is a list of four
                RGBA floating-point numbers (between 0 and 1)
            collision_color: optional, color to give to the collision model of
                the robot. Format is a list of four RGBA floating-point numbers
                (between 0 and 1)
            visual_color: optional, color to give to the visual model of
                the robot. Format is a list of four RGBA floating-point numbers
                (between 0 and 1)
        """
        ...
    
    def reload(self, new_geometry_object, geometry_type=...): # -> None:
        """Reload a geometry_object given by its name and its type"""
        ...
    
    def clean(self): # -> None:
        ...
    
    def delete(self, geometry_object, geometry_type): # -> None:
        ...
    
    def display(self, q=...): # -> None:
        """
        Display the robot at configuration q in the viewer by placing all the bodies
        """
        ...
    
    def updatePlacements(self, geometry_type): # -> None:
        ...
    
    def addGeometryObject(self, obj: pin.GeometryObject, color=...): # -> None:
        """Add a visual GeometryObject to the viewer, with an optional color."""
        ...
    
    def captureImage(self, w=..., h=...): # -> NDArray[Any]:
        """Capture an image from the Meshcat viewer and return an RGB array."""
        ...
    
    def displayCollisions(self, visibility): # -> None:
        """Set whether to display collision objects or not."""
        ...
    
    def displayVisuals(self, visibility): # -> None:
        """Set whether to display visual objects or not."""
        ...
    
    def displayFrames(self, visibility, frame_ids=..., axis_length=..., axis_width=...): # -> None:
        """Set whether to display frames or not."""
        ...
    
    def initializeFrames(self, frame_ids=..., axis_length=..., axis_width=...): # -> None:
        """Initializes the frame objects for display."""
        ...
    
    def updateFrames(self): # -> None:
        """
        Updates the frame visualizations with the latest transforms from model data.
        """
        ...
    
    def drawFrameVelocities(self, frame_id: int, v_scale=..., color=...): # -> None:
        ...
    


__all__ = ["MeshcatVisualizer"]
