"""
This type stub file was generated by pyright.
"""

import numpy as np
from .base_visualizer import BaseVisualizer

WITH_HPP_FCL_BINDINGS = ...
class Panda3dVisualizer(BaseVisualizer):
    """
    A Pinocchio display using panda3d engine.
    """
    def initViewer(self, viewer=..., load_model=...): # -> None:
        """Init the viewer by attaching to / creating a GUI viewer."""
        ...
    
    def loadViewerModel(self, group_name, color=...): # -> None:
        """Create a group of nodes displaying the robot meshes in the viewer."""
        ...
    
    def getViewerNodeName(self, geometry_object, geometry_type): # -> None:
        """Return the name of the geometry object inside the viewer."""
        ...
    
    def display(self, q=...): # -> None:
        """
        Display the robot at configuration q in the viewer by placing all the bodies.
        """
        ...
    
    def displayCollisions(self, visibility): # -> None:
        """Set whether to display collision objects or not."""
        ...
    
    def displayVisuals(self, visibility): # -> None:
        """Set whether to display visual objects or not."""
        ...
    
    def setBackgroundColor(self):
        ...
    
    def setCameraTarget(self, target):
        ...
    
    def setCameraPosition(self, position: np.ndarray):
        ...
    
    def setCameraZoom(self, zoom: float):
        ...
    
    def setCameraPose(self, pose: np.ndarray):
        ...
    
    def captureImage(self, w=..., h=...):
        ...
    
    def disableCameraControl(self):
        ...
    
    def enableCameraControl(self):
        ...
    
    def drawFrameVelocities(self, *args, **kwargs):
        ...
    


__all__ = ["Panda3dVisualizer"]
