"""
This type stub file was generated by pyright.
"""

import numpy as np
from . import BaseVisualizer

WITH_HPP_FCL_BINDINGS = ...
def create_capsule_markers(marker_ref, oMg, d, fl): # -> list[Any]:
    """Make capsule using two sphere and one cylinder"""
    ...

def SE3ToROSPose(oMg): # -> Pose:
    """Converts SE3 matrix to ROS geometry_msgs/Pose format"""
    ...

class RVizVisualizer(BaseVisualizer):
    """A Pinocchio display using RViz"""
    class Viewer:
        app = ...
        viz = ...
        viz_manager = ...
    
    
    def initViewer(self, viewer=..., windowName=..., loadModel=..., initRosNode=...): # -> Viewer | None:
        """
        Init RVizViewer by starting a ros node (or not) and creating an RViz window.
        """
        ...
    
    def loadViewerModel(self, rootNodeName=...): # -> None:
        """Create the displays in RViz and create publishers for the MarkerArray"""
        ...
    
    def clean(self): # -> None:
        """Delete all the objects from the whole scene"""
        ...
    
    def display(self, q=...): # -> None:
        """Display the robot at configuration q in the viz by placing all the bodies."""
        ...
    
    def displayCollisions(self, visibility): # -> None:
        """Set whether to display collision objects or not"""
        ...
    
    def displayVisuals(self, visibility): # -> None:
        """Set whether to display visual objects or not"""
        ...
    
    def sleep(self, dt): # -> None:
        ...
    
    def setBackgroundColor(self):
        ...
    
    def setCameraTarget(self, target):
        ...
    
    def setCameraPosition(self, position: np.ndarray):
        ...
    
    def setCameraZoom(self, zoom: float):
        ...
    
    def setCameraPose(self, pose: np.ndarray):
        ...
    
    def captureImage(self, w=..., h=...):
        ...
    
    def disableCameraControl(self):
        ...
    
    def enableCameraControl(self):
        ...
    
    def drawFrameVelocities(self, *args, **kwargs):
        ...
    


__all__ = ["RVizVisualizer"]
