"""
This type stub file was generated by pyright.
"""

from enum import Enum
from .base_visualizer import BaseVisualizer
from .gepetto_visualizer import GepettoVisualizer
from .meshcat_visualizer import MeshcatVisualizer
from .panda3d_visualizer import Panda3dVisualizer
from .rviz_visualizer import RVizVisualizer

class Visualizer(Enum):
    BASE = BaseVisualizer
    GEPETTO = GepettoVisualizer
    MESHCAT = MeshcatVisualizer
    PANDA3D = Panda3dVisualizer
    RVIZ = RVizVisualizer
    @classmethod
    def default(cls): # -> Any:
        """
        Allow user to choose their prefered viewer with eg.
        export PINOCCHIO_VIEWER=RVIZ.

        Otherwise, try to find one which is installed.
        """
        ...
    


