tick:
  rate_hz: 30.0
  mode: "ONCE_UNLESS_WOKEN_UP"
  while_running_max_block_ms: 100

state:
  joint_states_topic: "/joint_states"
  base_frame: "base_link"
  ee_frame: "tool0"
  tf_timeout_sec: 0.05
  state_stale_sec: 0.2

move_group:
  action_name: "/move_action"
  get_planning_scene_service_name: "/get_planning_scene"

execution:
  execute_traj_action_name: "/execute_trajectory"

planning:
  default_profile: "ompl_default"

servo:
  pause_service_name: "/servo_node/pause_servo"
  switch_command_type_service_name: "/servo_node/switch_command_type"
  status_topic: "/servo_node/status"

servo_joy_frontend:
  joy_topic: "/joy"
  twist_topic: "/servo_node/delta_twist_cmds"
  joint_topic: "/servo_node/delta_joint_cmds"
  pose_topic: "/servo_node/pose_target_cmds"
  command_frame: "tool0"
  deadzone: 0.10
  linear_scale: 0.25
  angular_scale: 0.75
  axis_linear:
    x: LEFTY
    y: LEFTX
    z_pos: TRIGGERRIGHT
    z_neg: TRIGGERLEFT
  axis_angular:
    x: RIGHTY
    y: RIGHTX
    z_pos: RIGHTSHOULDER
    z_neg: LEFTSHOULDER
  buttons:
    finish: START
    abort: BACK

monitor:
  monitor_namespace: "tesseract_monitor"
  env_name: ""
  wait_timeout_ms: 3000
