"""Shared topic and service names for MuJoCo Gen3 simulation nodes."""

SIM_NAMESPACE = "sim/gen3"
JOINT_STATE_TOPIC = f"{SIM_NAMESPACE}/state/joints"
RESET_SIM_SERVICE = f"{SIM_NAMESPACE}/reset"
PAUSE_SIM_SERVICE = f"{SIM_NAMESPACE}/pause"

CONTROLLER_NAMESPACE = "controller/gen3"
EFFORT_COMMAND_TOPIC = f"{CONTROLLER_NAMESPACE}/command/effort"
SET_GAINS_SERVICE = f"{CONTROLLER_NAMESPACE}/set_joint_gains"
FOLLOW_TRAJECTORY_ACTION = (
    f"{CONTROLLER_NAMESPACE}/follow_trajectory"
)

PLANNER_NAMESPACE = "planner/gen3"
QUINTIC_TRAJECTORY_SERVICE = f"{PLANNER_NAMESPACE}/plan_quintic"
POINT_TRAJECTORY_SERVICE = f"{PLANNER_NAMESPACE}/plan_point"
PLANNED_TRAJECTORY_TOPIC = f"{PLANNER_NAMESPACE}/planned_trajectory"

EXECUTOR_NAMESPACE = "executor/gen3"
EXECUTE_TRAJECTORY_SERVICE = f"{EXECUTOR_NAMESPACE}/execute"
TRACK_CURRENT_SERVICE = f"{EXECUTOR_NAMESPACE}/track_current"

__all__ = [
    "EXECUTE_TRAJECTORY_SERVICE",
    "EFFORT_COMMAND_TOPIC",
    "FOLLOW_TRAJECTORY_ACTION",
    "JOINT_STATE_TOPIC",
    "PAUSE_SIM_SERVICE",
    "PLANNED_TRAJECTORY_TOPIC",
    "PLANNER_NAMESPACE",
    "POINT_TRAJECTORY_SERVICE",
    "RESET_SIM_SERVICE",
    "SET_GAINS_SERVICE",
    "QUINTIC_TRAJECTORY_SERVICE",
    "TRACK_CURRENT_SERVICE",
]
