"""
This type stub file was generated by pyright.
"""

import numpy
import inspect
import sys
import hppfcl
from .pinocchio_pywrap_default import *
from .pinocchio_pywrap_default import __raw_version__, __version__
from . import utils
from .explog import exp, log
from hppfcl import CachedMeshLoader, CollisionGeometry, CollisionResult, Contact, DistanceResult, MeshLoader, StdVec_CollisionResult, StdVec_Contact, StdVec_DistanceResult
from .deprecated import *
from .robot_wrapper import RobotWrapper
from .shortcuts import *

submodules = inspect.getmembers(pinocchio_pywrap_default, inspect.ismodule)
if WITH_HPP_FCL:
    WITH_HPP_FCL_BINDINGS = ...
else:
    WITH_HPP_FCL_BINDINGS = ...
