"""
This type stub file was generated by pyright.
"""

class DeprecatedWarning(UserWarning):
    ...


def deprecated(instructions): # -> Callable[..., _Wrapped[..., Any, ..., Any]]:
    """Flags a method as deprecated.
    Args:
        instructions: A human-friendly string of instructions, such
            as: 'Please migrate to add_proxy() ASAP.'
    """
    ...

