"""
This type stub file was generated by pyright.
"""

from .robot_wrapper import RobotWrapper

class RomeoWrapper(RobotWrapper):
    def __init__(self, filename, package_dirs=..., verbose=...) -> None:
        ...
    
    def Mrh(self, q):
        ...
    
    def Jrh(self, q):
        ...
    
    def wJrh(self, q):
        ...
    
    def vrh(self, q, v):
        ...
    
    def Jlh(self, q):
        ...
    
    def Mlh(self, q):
        ...
    
    def Jlf(self, q):
        ...
    
    def Mlf(self, q):
        ...
    
    def Jrf(self, q):
        ...
    
    def Mrf(self, q):
        ...
    


__all__ = ["RomeoWrapper"]
