"""
This type stub file was generated by pyright.
"""

def npToTTuple(M): # -> tuple[Any, ...]:
    ...

def npToTuple(M): # -> tuple[Any, ...]:
    ...

def eye(n): # -> NDArray[float64]:
    ...

def zero(n): # -> NDArray[float64]:
    ...

def rand(n): # -> ndarray[Any, dtype[float64]]:
    ...

def isapprox(a, b, epsilon=...): # -> bool:
    ...

def mprint(M, name=..., eps=...): # -> None:
    """
    Matlab-style pretty matrix print.
    """
    ...

def fromListToVectorOfString(items):
    ...

__all__ = ["eye", "fromListToVectorOfString", "isapprox", "matrixToRpy", "mprint", "np", "npToTTuple", "npToTuple", "npl", "rand", "rotate", "rpyToMatrix", "zero"]
