"""
This type stub file was generated by pyright.
"""

import contextlib

def get_dll_paths(): # -> list[Path] | list[str]:
    ...

class PathManager(contextlib.AbstractContextManager):
    """Restore PATH state after importing Python module"""
    def add_dll_directory(self, dll_dir: str): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *exc_details): # -> None:
        ...
    


class DllDirectoryManager(contextlib.AbstractContextManager):
    """Restore DllDirectory state after importing Python module"""
    def add_dll_directory(self, dll_dir: str): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *exc_details): # -> None:
        ...
    


def build_directory_manager(): # -> DllDirectoryManager:
    ...

