"""
This type stub file was generated by pyright.
"""

import sys
import hppfcl
from .. import utils
from ..explog import exp, log
from ..pinocchio_pywrap_casadi import *
from ..pinocchio_pywrap_casadi import __raw_version__, __version__
from hppfcl import CachedMeshLoader, CollisionGeometry, CollisionResult, Contact, DistanceResult, MeshLoader, StdVec_CollisionResult, StdVec_Contact, StdVec_DistanceResult

if WITH_HPP_FCL:
    WITH_HPP_FCL_BINDINGS = ...
else:
    WITH_HPP_FCL_BINDINGS = ...
