monitor:
  monitor_namespace: tesseract_monitor
  env_name: fr3
  wait_timeout_ms: 3000

trajopt:
  default_num_steps: 20
  use_moveit_group_as_tesseract_manipulator: true
  fixed_tesseract_manipulator_group: manipulator
  enable_seed_cache: false
  enable_last_solution_cache: false
